import { getGoogleSheetsClient } from './lib/google';

export default async function handler(req: any, res: any) {
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    const spreadsheetId = process.env.GOOGLE_SHEETS_ID;
    if (!spreadsheetId) {
        return res.status(500).json({ error: 'Missing GOOGLE_SHEETS_ID environment variable' });
    }

    try {
        const { action, payload } = req.body;
        const sheets = getGoogleSheetsClient();

        if (action === 'insert_reference') {
            // payload: { procedimento, valor, dataCriacao, ativo }
            if (!payload.procedimento || payload.valor === undefined) {
                return res.status(400).json({ error: 'Missing procedimento or valor' });
            }

            const dataCriacao = payload.dataCriacao || new Date().toISOString();
            const statusAtivo = payload.ativo === false ? 'Inativo' : 'Ativo';
            const row = [payload.procedimento, dataCriacao, payload.valor, statusAtivo];

            const response = await sheets.spreadsheets.values.append({
                spreadsheetId,
                range: 'Ref_Procedimentos!A:D',
                valueInputOption: 'USER_ENTERED',
                insertDataOption: 'INSERT_ROWS',
                requestBody: { values: [row] },
            });

            return res.status(200).json({ success: true, updates: response.data.updates });
        }

        if (action === 'batch_insert_realizados') {
            // payload: { month, year, procedures: [{ paciente_id, proc, qtd, unit, valor_total }] }
            // This allows the frontend to send the pre-calculated `unit` and `valor_total` 
            // based on the historical `Ref_Procedimentos` table.
            if (!payload.procedimentos || !Array.isArray(payload.procedimentos)) {
                return res.status(400).json({ error: 'Missing procedimentos array' });
            }

            // sheet format: id, paciente_id, proc, mes, ano, qtd, unit, valor_total
            const rows = payload.procedimentos.map((p: any) => [
                p.id || '', // can be generated by sheets formula or empty
                p.paciente_id || '',
                p.proc || '',
                payload.month || '',
                payload.year || '',
                p.qtd || 1,
                p.unit || 0,
                p.valor_total || 0
            ]);

            const response = await sheets.spreadsheets.values.append({
                spreadsheetId,
                range: 'Procedimentos_Realizados!A:H',
                valueInputOption: 'USER_ENTERED',
                insertDataOption: 'INSERT_ROWS',
                requestBody: { values: rows },
            });

            return res.status(200).json({ success: true, updates: response.data.updates });
        }

        return res.status(400).json({ error: 'Invalid action' });
    } catch (error: any) {
        console.error('API Error:', error);
        return res.status(500).json({ error: error.message || 'Internal Server Error' });
    }
}
